### ISSUE TITLE
Rename simulation.velocityDecay to viscosity?

### ISSUE THREAD

**Issue by fdietze** [d3/d3-force#100]
The [docs](https://github.com/d3/d3-force#simulation_velocityDecay) for `simulation.velocityDecay()` state:
> ... **after** the application of any forces during a [tick](#simulation_tick), each node’s velocity is multiplied by 1 - _decay_ ...

This is not true for the implementation:

https://github.com/d3/d3-force/blob/master/src/simulation.js#L49
```javascript
    for (i = 0; i < n; ++i) {
      node = nodes[i];
      if (node.fx == null) node.x += node.vx *= velocityDecay;
      else node.x = node.fx, node.vx = 0;
      if (node.fy == null) node.y += node.vy *= velocityDecay;
      else node.y = node.fy, node.vy = 0;
    }
  }
```

It should probably be:
```javascript
node.x += node.vx;
node.vx *= velocityDecay;
```

**Comment by mbostock** [comment]
The “application of any forces” refers to the invocation of the registered forces (see [d3.forceX](https://github.com/d3/d3-force/blob/master/src/x.js#L11-L15) for an example), which typically modifying the nodes’ velocities, *node*.vx and *node*.vy.

The code you quoted is the application of the new velocities to the nodes’ positions, and yes, the velocity decay happens *after* the application of the new velocities to the new positions rather than before. But this is still after the “application of any forces” per the definition above.

We could change velocity decay to apply before applying the velocity, but I’m not sure this would be an improvement, and at least for me I think of it as applying “between” ticks rather than applying immediately.  Without a strong reason to change the behavior it’s safer to document the current behavior.

The README could make this clearer and you are welcome to open a pull request!

**Comment by fdietze** [comment]
I'm not sure I understand correctly.

When I do:
```javascript
> x = 0 // position
0
> v = 4 // velocity
4
> x += v *= 0.5
2
> x
2 // the position changed only by a fraction of the velocity, so the decay was applied before
```
Then the velocity got multiplied with `0.5` **before** it is applied to the position. This means that if I set the `velocityDecay` to `1`, my velocity gets multiplied with `1-1=0` before being applied to the position. So my nodes do not move at all. This is not what you explained:
>the velocity decay happens **after** the application of the new velocities to the new positions rather than before

**Comment by fdietze** [comment]
Now I found the description of the tick function which makes it very clear and fits the implementation:
> ... then decrements each node’s velocity by velocity × velocityDecay; lastly increments each node’s position by velocity.

But I'm wondering why it is implemented like that. I wanted to set the `velocityDecay = 1`, to apply the velocities once, forget the old values und recalculate them in the force-functions based on the new positions. To my surprise, the nodes didn't move at all. In the current implementation it is neither possible to reset the velocities like I wanted to, nor apply 100% of a velocity vector to a node's position.

What was your motivation to decay the velocity before application?

**Comment by mbostock** [comment]
Sorry, I described it wrongly above. Yes, the “velocity decay” is applied to dampen the velocities *before* they are applied to the nodes’ positions.

This parameter in v3 was called [*force*.friction parameter](https://github.com/d3/d3-3.x-api-reference/blob/master/Force-Layout.md#friction); see [CHANGES](https://github.com/d3/d3/blob/master/CHANGES.md#forces-d3-force). It was originally supposed to be analogous to a [drag force](https://en.wikipedia.org/wiki/Drag_\(physics\)), though the name “drag” was too confusing in relation to the [interaction method of dragging](https://github.com/d3/d3-drag) and there was already a [*force*.drag](https://github.com/d3/d3-3.x-api-reference/blob/master/Force-Layout.md#drag) in v3.

(Also, the v3 “friction” force was proportional to the velocity, rather than proportional to the square of the velocity, but that’s reasonable if you’re simulating [viscous resistance](https://en.wikipedia.org/wiki/Drag_\(physics\)#Very_low_Reynolds_numbers:_Stokes.27_drag).)

So… perhaps this parameter should be named “viscosity” rather than “velocity decay”.

You could implement a “velocity decay” that applies between ticks as an other force, and then set *simulation*.velocityDecay to 0.
