### ISSUE TITLE
simulation.nodes(data).on('tick', ticked) failing for large data

### ISSUE THREAD

**Issue by ivmarkp** [d3/d3-force#118]
I am trying to generate a bubble graph for 500+ objects and it turns out that it doesn't work for data arrays of size exceeding 300 or so (this is not a hard limit, just from what I observed). Basically, if the data array size exceeds that limit, all the bubbles are concentrated on a single x, y position.

This is what I'm doing:

```typescript

simulation.nodes(data)
          .on('tick', ticked);

      
function ticked() {
	debugger;

	circle.attr("cx", function (d: any) {
	  return d.x;
	})
	.attr("cy", function (d: any) {
		return d.y;
	});
}
```
The breakpoint inside `ticked()` doesn't get hit every time when the data size is 300+ in my case and when that breakpoint is hit, bubbles do appear distinctively instead of getting jammed at one location.

Is there a workaround for this issue?

**Comment by mbostock** [comment]
There’s no hard limit on the number of nodes; you can have as many nodes as you like, depending on how fast your computer is. 

It’s not possible to debug this without seeing your full code in a live example, but here are some things I would investigate: Are you initializing the positions of the nodes before starting the simulation? Are any of those positions invalid? Are any of them coincident? Do you have forces which vary from node to node? Probably want is happening here is that the positions or forces are invalid (NaN) due to some aspect of the data or forces you have configured on the simulation.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Stack Overflow provides a better collaborative forum: thousands of D3-related questions have been asked there, and some answers may be relevant to you.

When asking for help, please include a link to demonstrate the issue, preferably as an [Observable notebook](https://beta.observablehq.com). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by mbostock** [comment]
Regarding the code you posted, I’ll repeat my previous comment:

> When asking for help, please include a link to demonstrate the issue, preferably as an [Observable notebook](https://beta.observablehq.com). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

The key point here is that it must be *reproducible*. It’s extremely unlikely that the problem exists in the snippet you posted, since that snippet is doing very few things. As I said, my guess is that the problem exists within the definition of *data*, but I’d need to be able to run the code with your data to investigate any further.

**Comment by ivmarkp** [comment]
Wish I could share the data but for some reasons it's confidential.
