### ISSUE TITLE
Description of the json format representing a GRAPH

### ISSUE THREAD

**Issue by ShiinaMitsuki** [d3/d3-force#140]
Sorry for bothering, but could any body tells me where can I find the DESCRIPTION about the json format which representing a graph?

```
{
  "nodes": [
    {"id": "Myriel", "group": 1},
    {"id": "Napoleon", "group": 1},
    {"id": "Mlle.Baptistine", "group": 1},
    {"id": "Mme.Magloire", "group": 1},
],
"links": [
    {"source": "Napoleon", "target": "Myriel", "value": 1},
    {"source": "Mlle.Baptistine", "target": "Myriel", "value": 8},
    {"source": "Mme.Magloire", "target": "Myriel", "value": 10},
    {"source": "Mme.Magloire", "target": "Mlle.Baptistine", "value": 6},
]
}
```
eg:
1. How many keys do we have?
2. whtat is "value" for and "group"?
3. How to add some properties to the "node" and "link"?
.etc

Thanks in advance!!

**Comment by bionicles** [comment]
Keys are just strings and you can have as many as fit in memory
Value is probably for weights or coloring. You can do whatever you want, link value is not mission critical
To add properties if you need to modify the svg elements use css classes or .attr. To modify the json in this case, we have arrays so you must loop through the array, find the node in question by key:value, and then update the node, and replace it in the selection. Pretty craptastic and slow especially in React with 1 way data flow, or if you're doing immutable objects, you've got to copy everything every refresh, which is somewhat moronic. 

I find it easier to assign a uuidv4 to each node and link, and to make these a map. You can pass Object.values(nodes) to get the items, but if we treat nodes and links as maps instead of arrays, some things become much faster O(1) lookup of specific nodes by their id. This means we can update, delete, select, deselect much faster. 

However, even with objects instead of arrays of "nodes" and "links" there's no good traversal solution so we have to make one; probably a class which returns self. The definition of "graph" is "index-free adjacency" and thus, D3 Force Graphs are not actually graphs, as we must loop through arrays to do traversals, it does not scale. Also the bounding box calculation must be incorporated in the tick actions which is super slow, there is probably a big opportunity to accelerate constraints so nodes stay within a rectangle without a O(N) calculation every tick. Could be nice to run multiple "ticks" per constraint calculation, then schedule an animation. 

If you want to look at nodes and links, just "inspect" in chrome and click on a node or link in the svg. D3 binds data to the svg so it will show the xy coords, etc etc

if we want a really legit graph software, we can use d3 for some aspects, but the lack of traversals, being forced to use arrays, and the hackerish constraint-by-tick are limiting. Good idea is to make your own graph first, then hook that up to d3 for visualization. D3 is not a graph database, but it does crush a number of forces well

**Comment by mbostock** [comment]
There isn’t a set JSON format; the behavior is controlled by the data structures and accessor functions you pass to [d3.forceSimulation](https://github.com/d3/d3-force/blob/master/README.md#simulation) and [d3.forceLink](https://github.com/d3/d3-force/blob/master/README.md#links). Specifically see [*link*.id](https://github.com/d3/d3-force/blob/master/README.md#link_id) for examples.
