### ISSUE TITLE
Why center doesn't use alpha or velocity?

### ISSUE THREAD

**Issue by dballesteros7** [d3/d3-force#55]
I just migrated to v4 but I can't manage to get the same behavior as before and so far the culprit seems to be the center force.

It moves my points very abruptly, looking at the code it seems odd that it doesn't use velocity or alpha to do the ticks. Is this intended?

**Comment by mbostock** [comment]
Yes. Think of d3.forceCenter as shifting the viewport, rather than shifting the graph, such that the graph is always at the center of the viewport. In contrast d3.forceX and d3.forceY push the nodes, and correspondingly apply momentum. The old *force*.size and *force*.gravity in v3 are equivalent to the new d3.forceX and d3.forceY in v4. There is no equivalent to d3.forceCenter in v3.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
