### ISSUE TITLE
Filter function for x and y ?

### ISSUE THREAD

**Issue by Mavromatika** [d3/d3-force#68]
Hi,
I have slightly modified the code for the x() and y() functions in a project I'm working on, to easily position certain groups of nodes. 
I've just added an applyTo() function in which one can define an accessor to select only certain nodes. In initialize() the nodes are then filtered to keep only the relevant ones. 

I don't know enough about github to create a pull request, and I'm also not confident enough about my code, so please pardon me if I'm not using the right channel to propose this.

**Comment by mbostock** [comment]
Thanks for the suggestion. However, I’m not sure I understand the usefulness of applyTo. If you want to apply a force selectively, the recommended way for [d3.forceX](https://github.com/d3/d3-force/blob/master/README.md#forceX) is to have your [*x*.x](https://github.com/d3/d3-force/blob/master/README.md#x_x) return NaN (or undefined), or have [*x*.strength](https://github.com/d3/d3-force/blob/master/README.md#x_strength) return zero. The force will still iterate over every node for each application (tick), however; if you want to avoid that, then I’d recommend writing a custom force copying the implementation of d3.forceX that allows you to specify the array of affected *nodes* explicitly rather than using the array of nodes passed to [*force*.initialize](https://github.com/d3/d3-force/blob/master/README.md#force_initialize).

**Comment by Mavromatika** [comment]
Thank you for your reply. I think I understand how forces work better now thanks to your response.
