### ISSUE TITLE
Collide force generating Infinity coordinates?

### ISSUE THREAD

**Issue by lxpollitt** [d3/d3-force#77]
I think that this line might sometimes be generating Infinity, and I'm assuming that isn't a great outcome:

https://github.com/d3/d3-force/blob/master/src/collide.js#L51

I think because jiggle() can generate very small numbers depending on luck of random(), and when you throw these into a sqrt() calculation it makes them even smaller.

e.g. This will typically generate a lot of "ooh!":

        for (var i=0; i<1000000; i++){
            if (!isFinite(1/Math.sqrt((Math.random() - 0.5) * 1e-6))) {
                console.error("ooh!");
            }
        }

The context here is that I'm trying to track down an "Aw snap" error in Chrome.  It seems to coincide with seeing Infinity x or y coordinates during simulation (though I'm not yet convinced that the Chrome hang is actually caused by the Infinity values).

**Comment by mbostock** [comment]
Your code generates NaN’s because Math.random() - 0.5 is negative about half the time, and Math.sqrt of a negative number returns NaN, and isFinite(NaN) returns false. In the source you linked, `l` is always positive (because it is the sum of a series of squares, initialized to `l = x * x + y * y`, and possibly incremented by `l += x * x` where `x` is a small, deterministic random number), so this can’t happen.

So, if you’re seeing coordinates that have the value Infinity, it’s coming from somewhere else. If you’d like me to investigate, you must post a link to an example that reproduces the issue, as described in [Reporting an Issue](https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf).

**Comment by lxpollitt** [comment]
Thanks Mike.  You're right about my test code being nonsense!  I'll keep searching and get back to you if I manage to get to the bottom of it.
