### ISSUE TITLE
Multiple networks issue

### ISSUE THREAD

**Issue by pdubey84** [d3/d3-force#93]
I've been trying to solve this for days now with no luck... Any help is greatly appreciated.

**The scenario:**
- I have d3 rendering multiple networks.
- It consists of single nodes plus multiple connected node networks.
- I am trying to attach d3-force (simulation) so that the nodes dont overlap when dragged and the entire network maintains relative positioning.
- Am using the manybody force.

**The problem:**
- When the simulation loads (simulation.restart()), the entire network keeps spreading apart.
- All nodes/networks keep moving away indefinitely.
- Even when nodes from one network are dragged, all other networks move.

**Expected behavior** 
- If its single nodes, they shouldn't move unless dragged
- When a connected network is dragged, only that network moves and nothing else moves
- If a connected network is dragged onto itself, it opens up
- if one network is dragged onto another network, then they both move away and maintain relative distance.
- If the networks are away from each other then dragging one shouldn't move or affect anything else.
- The example is a relatively smaller network, I have to make it work for more complex and larger networks as well. with thousands of nodes+tens of thousands of links

Heres a small fiddle : https://jsfiddle.net/pdubey84/or0tn49k/2/

**Comment by steveharoz** [comment]
1. The nodes spread apart because of the negative charge force. They stop moving apart once all the nodes are `distanceMax` apart (50 for your jsfiddle)
2. They don't move away indefinitely. But as long as the simulation is active, they will keep wiggling to try to find an optimal position.
3. The reason why all nodes move when any node is dragged is that `simulation.alphaTarget(0.7).restart()` adds energy to the entire simulation, not just the node being dragged.

Commenting out `simulation.alphaTarget(0.7).restart()` and `simulation.alphaTarget(0).restart()` from your jsfiddle may be what you want.

In the future, this kind of question would be more appropriate for stackoverflow.com

**Comment by mbostock** [comment]
Thanks for fielding this question, @steveharoz!

**Comment by pdubey84** [comment]
Thanks for the response @steveharoz  I tried your suggestion but then the drag/drop of nodes doesnt work. I was wondering if there was a way to apply multiple simulations on different networks so they dont interfere with each other?

**Comment by steveharoz** [comment]
@pdubey84 That'd involve a complex simulation system, which is beyond the scope of d3-force.

**Comment by pdubey84** [comment]
Thanks for  your prompt response @steveharoz
